-- Create table for Sell Requests (Sell Your Phone)
create table if not exists public.sell_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  phone_name text not null,
  year text,
  details text,
  specifications text,
  contact_number text not null,
  images text[] default array[]::text[],
  status text default 'pending'
);

-- Create table for Item Requests (Request Item)
create table if not exists public.item_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  item_name text not null,
  details text,
  contact_number text not null,
  image_url text,
  status text default 'pending'
);

-- Enable Row Level Security (RLS)
alter table public.sell_requests enable row level security;
alter table public.item_requests enable row level security;

-- Create policies to allow anyone (anon) to insert data
create policy "Enable insert for all users" on public.sell_requests
  for insert with check (true);

create policy "Enable insert for all users" on public.item_requests
  for insert with check (true);

-- Create policies to allow anyone (anon) to read their own data (optional, or allow public read if needed for admin)
-- For this app, typically the Admin Dashboard needs to read all.
-- Since the Admin Dashboard uses the same anon key in this codebase (simple setup), we allow read for all.
-- In a real production app with auth, you'd restrict this.
create policy "Enable read for all users" on public.sell_requests
  for select using (true);

create policy "Enable read for all users" on public.item_requests
  for select using (true);

-- Storage bucket for images
insert into storage.buckets (id, name, public) 
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Storage policies
create policy "Give public access to product-images" on storage.objects
  for select using (bucket_id = 'product-images');

create policy "Allow public uploads to product-images" on storage.objects
  for insert with check (bucket_id = 'product-images');
